import { NextResponse } from "next/server";
import { desc, eq } from "drizzle-orm";
import ExcelJS from "exceljs";
import { guard, jsonError } from "@/lib/api";
import { db } from "@/lib/db";
import { aiReports, risks, users } from "@/lib/schema";
import {
  builderSchema,
  readReportParameters,
  type BuilderPayload,
  type MetricTable,
} from "@/lib/report-config";
import { assembleMetricTables } from "@/lib/report-data";

export const maxDuration = 60;

const HEADER_FILL: ExcelJS.Fill = {
  type: "pattern",
  pattern: "solid",
  fgColor: { argb: "FF0A1420" },
};
const HEADER_FONT: Partial<ExcelJS.Font> = { bold: true, color: { argb: "FFFFFFFF" } };

function styleHeaderRow(row: ExcelJS.Row) {
  row.eachCell((cell) => {
    cell.fill = HEADER_FILL;
    cell.font = HEADER_FONT;
  });
}

function autoWidth(sheet: ExcelJS.Worksheet, max = 70) {
  sheet.columns.forEach((col) => {
    let width = 10;
    col.eachCell?.({ includeEmpty: false }, (cell) => {
      const len = String(cell.value ?? "").length;
      if (len + 2 > width) width = len + 2;
    });
    col.width = Math.min(width, max);
  });
}

function sanitizeSheetName(name: string, used: Set<string>): string {
  let base = name.replace(/[\\/?*[\]:]/g, " ").trim().slice(0, 28) || "Sheet";
  let candidate = base;
  let i = 2;
  while (used.has(candidate)) candidate = `${base.slice(0, 25)} ${i++}`;
  used.add(candidate);
  return candidate;
}

function addMetricSheet(wb: ExcelJS.Workbook, table: MetricTable, used: Set<string>) {
  const sheet = wb.addWorksheet(sanitizeSheetName(table.title, used));
  styleHeaderRow(sheet.addRow(table.columns));
  if (table.rows.length === 0) {
    sheet.addRow(["No data in scope"]);
  } else {
    for (const row of table.rows) sheet.addRow(row);
  }
  autoWidth(sheet);
}

/** Fallback default metrics when a report predates the builder snapshot. */
function fallbackPayload(parameters: unknown, reportType: string): BuilderPayload {
  const raw =
    parameters && typeof parameters === "object"
      ? (parameters as Record<string, unknown>)
      : {};
  const legacy = builderSchema.safeParse({
    reportType: reportType === "deep_analysis" ? "risk_summary" : reportType,
    range: typeof raw.range === "string" ? raw.range : "all",
    metrics: ["severity_distribution", "category_breakdown", "response_status"],
    sources: [],
  });
  return legacy.success
    ? legacy.data
    : builderSchema.parse({
        reportType: "risk_summary",
        range: "all",
        metrics: ["severity_distribution", "category_breakdown", "response_status"],
      });
}

/** Render a persisted AI report as an Excel workbook: the report text plus
 *  one sheet per computed metric table (from the stored snapshot, or
 *  regenerated live for legacy reports). */
export async function GET(_request: Request, ctx: { params: Promise<{ id: string }> }) {
  const g = await guard("view", "ai_report");
  if (g.error) return g.error;

  const { id } = await ctx.params;
  if (!/^[0-9a-f-]{36}$/i.test(id)) return jsonError("Report not found.", 404);

  const [row] = await db
    .select({
      id: aiReports.id,
      title: aiReports.title,
      reportType: aiReports.reportType,
      content: aiReports.content,
      parameters: aiReports.parameters,
      createdAt: aiReports.createdAt,
      generatedBy: users.fullName,
    })
    .from(aiReports)
    .leftJoin(users, eq(aiReports.generatedBy, users.id))
    .where(eq(aiReports.id, id))
    .limit(1);

  if (!row) return jsonError("Report not found.", 404);

  try {
    const wb = new ExcelJS.Workbook();
    wb.creator = "COMRiC Workspace";
    wb.created = row.createdAt;
    const usedNames = new Set<string>();

    // Sheet 1: report meta + full text.
    const report = wb.addWorksheet(sanitizeSheetName("Report", usedNames));
    styleHeaderRow(report.addRow(["COMRiC WORKSPACE - Confidential"]));
    report.addRow([]);
    report.addRow(["Title", row.title]);
    report.addRow(["Type", row.reportType.replace(/_/g, " ")]);
    report.addRow(["Generated by", row.generatedBy ?? "Unknown"]);
    report.addRow([
      "Generated on",
      row.createdAt.toLocaleDateString("en-ZA", { day: "numeric", month: "short", year: "numeric" }),
    ]);
    report.addRow([]);
    styleHeaderRow(report.addRow(["Report content"]));
    for (const line of row.content.split("\n")) {
      report.addRow([line]);
    }
    report.getColumn(1).width = 24;
    report.getColumn(2).width = 60;
    report.getColumn(1).alignment = { vertical: "top", wrapText: false };

    // Metric sheets: reuse the persisted snapshot; otherwise compute live.
    const stored = readReportParameters(row.parameters);
    let tables = stored.metrics ?? [];
    if (tables.length === 0) {
      const payload = stored.builder ?? fallbackPayload(row.parameters, row.reportType);
      const withMetrics =
        payload.metrics.length > 0
          ? payload
          : {
              ...payload,
              metrics: [
                "severity_distribution",
                "category_breakdown",
                "response_status",
              ] as BuilderPayload["metrics"],
            };
      tables = await assembleMetricTables(withMetrics).catch(() => []);
    }

    if (tables.length > 0) {
      for (const table of tables) addMetricSheet(wb, table, usedNames);
    } else {
      // Last resort: a Register sheet of current risks so the workbook is
      // never data-free.
      const registerRows = await db
        .select({
          title: risks.title,
          category: risks.category,
          severity: risks.severity,
          status: risks.status,
          createdAt: risks.createdAt,
        })
        .from(risks)
        .orderBy(desc(risks.createdAt))
        .limit(200);
      const sheet = wb.addWorksheet(sanitizeSheetName("Register", usedNames));
      styleHeaderRow(sheet.addRow(["Title", "Category", "Severity", "Status", "Created"]));
      if (registerRows.length === 0) {
        sheet.addRow(["No risks recorded"]);
      } else {
        for (const r of registerRows) {
          sheet.addRow([
            r.title,
            r.category,
            r.severity,
            r.status,
            r.createdAt.toLocaleDateString("en-ZA"),
          ]);
        }
      }
      autoWidth(sheet);
    }

    const buffer = await wb.xlsx.writeBuffer();
    const filename = `${row.title.replace(/[^\w\d-]+/g, "-").replace(/-+/g, "-").toLowerCase()}.xlsx`;
    return new NextResponse(new Uint8Array(buffer as ArrayBuffer), {
      status: 200,
      headers: {
        "content-type":
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "content-disposition": `attachment; filename="${filename}"`,
        "cache-control": "no-store",
      },
    });
  } catch (err) {
    console.error("XLSX render failed", err);
    return jsonError("Excel export failed.", 500);
  }
}
