import Link from "next/link";
import { notFound } from "next/navigation";
import { eq } from "drizzle-orm";
import { ArrowLeft, Download } from "lucide-react";
import { db } from "@/lib/db";
import { aiReports, users } from "@/lib/schema";
import { Card, PageHeader } from "@/components/ui";
import { Markdown } from "@/components/markdown";

export const dynamic = "force-dynamic";

const TYPE_LABELS: Record<string, string> = {
  risk_summary: "Risk Summary",
  sector_report: "Sector Report",
  research_digest: "Research Digest",
  deep_analysis: "Deep Analysis",
};

export default async function ArchiveDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  if (!/^[0-9a-f-]{36}$/i.test(id)) notFound();

  const [report] = await db
    .select({
      id: aiReports.id,
      title: aiReports.title,
      reportType: aiReports.reportType,
      content: aiReports.content,
      createdAt: aiReports.createdAt,
      generatedBy: users.fullName,
    })
    .from(aiReports)
    .leftJoin(users, eq(aiReports.generatedBy, users.id))
    .where(eq(aiReports.id, id))
    .limit(1);

  if (!report) notFound();

  return (
    <div className="animate-rise">
      <Link
        href="/archive"
        className="mb-4 inline-flex items-center gap-1.5 text-sm font-bold text-muted hover:text-cyber"
      >
        <ArrowLeft className="h-4 w-4" /> Back to archive
      </Link>
      <PageHeader
        title={report.title}
        subtitle={`${TYPE_LABELS[report.reportType] ?? report.reportType} · Generated by ${report.generatedBy ?? "Unknown"} · ${report.createdAt.toLocaleDateString(
          "en-ZA",
          { day: "numeric", month: "long", year: "numeric" },
        )}`}
        actions={
          <a
            href={`/api/reports/${report.id}/pdf`}
            className="inline-flex items-center gap-2 rounded-brand bg-cyber px-4 py-2 font-display text-sm font-bold text-black transition-all duration-150 hover:brightness-110"
          >
            <Download className="h-4 w-4" /> Download PDF
          </a>
        }
      />
      <Card className="max-w-4xl p-8">
        <Markdown content={report.content} />
      </Card>
    </div>
  );
}
